app = "alternative-nyheter"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.railway"

[env]
  ENV = "prod"
  LOG_LEVEL = "INFO"
  ALLOWED_ORIGINS = "*"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256